server:
  port: 8888

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  mail:
    host: smtp.gmail.com
    ## 587(TLS) 465(SSL) 25(AUTH)
    port: 587
    username: cmc.ntduc@gmail.com
    password: Tu1den9a@
