spring:
  jpa:
    show-sql: true
## PostgreSQL
  datasource:
    url: jdbc:postgresql://ls-b7a5a468b8021abe51cd24707ed287cda341f4a7.cwbwjnv1r6bv.ap-southeast-1.rds.amazonaws.com:5432/demo_base
    username: dbmasteruser
    password: H]P!N4?Fg>pY#2#YJL1WC=HB+gwBOewt
## Mail
  mail:
    host: smtp.gmail.com
    ##  587(TLS) 465(SSL) 25(AUTH)
    port: 587
    username: cmc.ntduc@gmail.com
    password: Tu1den9a@
